package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// BuildChezmoiIgnore assembles the full .chezmoiignore content from global
// entries and per-recipe entries. Recipe sections are sorted alphabetically.
// Recipes with empty content are skipped.
func BuildChezmoiIgnore(globalEntries []string, recipeEntries map[string]string) string {
	var b strings.Builder
	b.WriteString("# Generated by chezmoi-recipes. DO NOT EDIT.\n")

	if len(globalEntries) > 0 {
		b.WriteString("\n# Global\n")
		for _, entry := range globalEntries {
			b.WriteString(entry)
			b.WriteByte('\n')
		}
	}

	names := make([]string, 0, len(recipeEntries))
	for name := range recipeEntries {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		content := strings.TrimRight(recipeEntries[name], "\n")
		if content == "" {
			continue
		}
		fmt.Fprintf(&b, "\n# Recipe: %s\n", name)
		b.WriteString(content)
		b.WriteByte('\n')
	}

	return b.String()
}

// MergeChezmoiIgnore generates the full .chezmoiignore content and writes it
// to sourceDir/.chezmoiignore.
func MergeChezmoiIgnore(sourceDir string, globalEntries []string, recipeEntries map[string]string) error {
	content := BuildChezmoiIgnore(globalEntries, recipeEntries)
	dest := filepath.Join(sourceDir, ".chezmoiignore")
	if err := os.WriteFile(dest, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing .chezmoiignore: %w", err)
	}
	return nil
}
