package setup

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBuildChezmoiIgnore_GlobalEntriesOnly(t *testing.T) {
	result := BuildChezmoiIgnore([]string{"scripts/"}, nil)

	if !strings.Contains(result, "# Generated by chezmoi-recipes") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "scripts/") {
		t.Error("missing global entry")
	}
}

func TestBuildChezmoiIgnore_SingleRecipe(t *testing.T) {
	entries := map[string]string{
		"alacritty": "{{ if .isContainer }}\nprivate_dot_config/alacritty/\n{{ end }}\n",
	}
	result := BuildChezmoiIgnore([]string{"scripts/"}, entries)

	if !strings.Contains(result, "# Recipe: alacritty") {
		t.Error("missing recipe section header")
	}
	if !strings.Contains(result, "private_dot_config/alacritty/") {
		t.Error("missing recipe ignore entry")
	}
}

func TestBuildChezmoiIgnore_MultipleRecipes_SortedAlphabetically(t *testing.T) {
	entries := map[string]string{
		"cartage":   "{{ if .isContainer }}\ncartage-stuff\n{{ end }}\n",
		"alacritty": "{{ if .isContainer }}\nalacritty-stuff\n{{ end }}\n",
	}
	result := BuildChezmoiIgnore([]string{"scripts/"}, entries)

	aIdx := strings.Index(result, "# Recipe: alacritty")
	cIdx := strings.Index(result, "# Recipe: cartage")
	if aIdx < 0 || cIdx < 0 {
		t.Fatalf("missing recipe sections in:\n%s", result)
	}
	if aIdx > cIdx {
		t.Error("alacritty should appear before cartage (alphabetical order)")
	}
}

func TestBuildChezmoiIgnore_TemplateSyntaxPreserved(t *testing.T) {
	entries := map[string]string{
		"alacritty": "{{ if .isContainer }}\nprivate_dot_config/alacritty/\n{{ end }}\n",
	}
	result := BuildChezmoiIgnore(nil, entries)

	if !strings.Contains(result, "{{ if .isContainer }}") {
		t.Error("template syntax not preserved")
	}
	if !strings.Contains(result, "{{ end }}") {
		t.Error("template end not preserved")
	}
}

func TestBuildChezmoiIgnore_EmptyRecipeContentSkipped(t *testing.T) {
	entries := map[string]string{
		"alacritty": "has content\n",
		"empty":     "",
		"whitespace": "\n\n",
	}
	result := BuildChezmoiIgnore(nil, entries)

	if strings.Contains(result, "# Recipe: empty") {
		t.Error("empty recipe should be skipped")
	}
	if strings.Contains(result, "# Recipe: whitespace") {
		t.Error("whitespace-only recipe should be skipped")
	}
	if !strings.Contains(result, "# Recipe: alacritty") {
		t.Error("non-empty recipe should be present")
	}
}

func TestMergeChezmoiIgnore_Idempotent(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	t.Setenv("XDG_DATA_HOME", t.TempDir())

	sourceDir := t.TempDir()
	global := []string{"scripts/"}
	entries := map[string]string{
		"alacritty": "private_dot_config/alacritty/\n",
	}

	if err := MergeChezmoiIgnore(sourceDir, global, entries); err != nil {
		t.Fatalf("first MergeChezmoiIgnore() error = %v", err)
	}
	first, err := os.ReadFile(filepath.Join(sourceDir, ".chezmoiignore"))
	if err != nil {
		t.Fatal(err)
	}

	if err := MergeChezmoiIgnore(sourceDir, global, entries); err != nil {
		t.Fatalf("second MergeChezmoiIgnore() error = %v", err)
	}
	second, err := os.ReadFile(filepath.Join(sourceDir, ".chezmoiignore"))
	if err != nil {
		t.Fatal(err)
	}

	if string(first) != string(second) {
		t.Errorf("content differs between runs:\nfirst:\n%s\nsecond:\n%s", first, second)
	}
}

func TestMergeChezmoiIgnore_WritesFile(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	t.Setenv("XDG_DATA_HOME", t.TempDir())

	sourceDir := t.TempDir()
	entries := map[string]string{
		"alacritty": "private_dot_config/alacritty/\n",
	}

	if err := MergeChezmoiIgnore(sourceDir, []string{"scripts/"}, entries); err != nil {
		t.Fatalf("MergeChezmoiIgnore() error = %v", err)
	}

	data, err := os.ReadFile(filepath.Join(sourceDir, ".chezmoiignore"))
	if err != nil {
		t.Fatalf("file not written: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "scripts/") {
		t.Error("missing global entry")
	}
	if !strings.Contains(content, "# Recipe: alacritty") {
		t.Error("missing recipe section")
	}
}
